mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}

recaptcha.secret=${RECAPTCHA_SECRET}
recaptcha.site-key=${RECAPTCHA_SITE_KEY}

db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
